modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "wayfinder"
version = "${version}"
displayName = "Wayfinder"
authors = "beeisyou"
description = '''
Oh you want a map so badly? Draw it yourself then
'''
#logoFile = ""

[[dependencies.wayfinder]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wayfinder]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "wayfinder.mixins.json"
